export const INVENTORY_COLLECTION = 'IDEVICECARE_INVENTORY';
export const CUSTOMERS_COLLECTION = 'IDEVICECARE_CUSTOMERS';
export const TRANSACTIONS_COLLECTION = 'IDEVICECARE_TRANSACTIONS';
export const SUPPLIERS_COLLECTION = 'IDEVICECARE_SUPPLIERS';
